config/routes.rb
Rails.application.routes.draw do

  
  devise_for :owners, path: 'owners', controllers: 
    {registrations: "owners/registrations", 
     sessions: "owners/sessions",
     passwords: "owners/passwords"  }

  devise_for :account_holders, path: 'account_holders', controllers: 
    {registrations: "account_holders/registrations",
     sessions: "account_holders/sessions", 
     passwords: "account_holders/passwords" }

  resources :profiles, only: [:show, :edit, :update]

  get 'dashboard', to: 'owners#dashboard'

  get 'confirm', to: :confirm, controller: 'account_holders'
  
  root to: 'pages#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account_holder.rb
class AccountHolder < ApplicationRecord

  validates_uniqueness_of :phone
  validates :phone, phone: { possible: false, allow_blank: false, types: [:mobile] }
  before_create :build_profile
  has_one :profile
  

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :sms_activable

  private
  
end

app/controllers/account_holders/confirmations_controller.rb
class AccountHolders::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/account_holders/omniauth_callbacks_controller.rb
class AccountHolders::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/account_holders/passwords_controller.rb
class AccountHolders::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/account_holders/registrations_controller.rb
class AccountHolders::RegistrationsController < Devise::RegistrationsController
# before_action :configure_sign_up_params, only: [:create]
# before_action :configure_account_update_params, only: [:update]
  before_action :configure_permitted_parameters, only: [:new, :create]


  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end
  def after_inactive_sign_up_path_for(resource)
    new_user_session_path
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:phone])
  end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  def after_sign_up_path_for(resource)
    profile_path(resource)
  end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/account_holders/sessions_controller.rb
class AccountHolders::SessionsController < Devise::SessionsController
# before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/account_holders/unlocks_controller.rb
class AccountHolders::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/account_holders_helper.rb
module AccountHoldersHelper
end

app/views/account_holders/_form.html.erb
<%= form_for(account_holder) do |f| %>
  <% if account_holder.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(account_holder.errors.count, "error") %> prohibited this account_holder from being saved:</h2>

      <ul>
      <% account_holder.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/account_holders/edit.html.erb
<h1>Editing Account Holder</h1>

<%= render 'form', account_holder: @account_holder %>

<%= link_to 'Show', @account_holder %> |
<%= link_to 'Back', account_holders_path %>

app/views/account_holders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Account Holders</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @account_holders.each do |account_holder| %>
      <tr>
        <td><%= link_to 'Show', account_holder %></td>
        <td><%= link_to 'Edit', edit_account_holder_path(account_holder) %></td>
        <td><%= link_to 'Destroy', account_holder, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Account Holder', new_account_holder_path %>

app/views/account_holders/new.html.erb
<h1>New Account Holder</h1>

<%= render 'form', account_holder: @account_holder %>

<%= link_to 'Back', account_holders_path %>

app/views/account_holders/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_account_holder_path(@account_holder) %> |
<%= link_to 'Back', account_holders_path %>